config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :carts
  resources :products
  resources :profiles
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'market#home'
  get '/', to: 'market#home'
  get '/category', to: 'market#home'
  get '/about', to: 'market#about'
  get '/contact', to: 'market#contact'

  get '/categories/:category', to: 'products#category'

  get '/products/seller/:seller_id', to: 'products#sellers_product_list', as: 'sellers_product_list'

  post '/transactions', to: 'transactions#create'

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :picture

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :suburb, presence: false
  validates :postcode, presence: true
  validates :mobile_number, presence: true, format: { with: /\d{10}/, message: "Please enter valid mobile number"}
  validates :picture, presence: false
  validates :abn, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # Get all users in the community page
  # Get current users latest profile
  def index
    @profiles = Profile.all
    @profile = Profile.where(user: current_user).last
  end


  # Get current users latest profile
  def show
    @profile = Profile.where(user: current_user).last
  end

  # Initialize a profile
  def new
    @profile = Profile.new

  end

  # GET current users latest profile
  def edit
    @profile = Profile.where(user: current_user).last
  end

  # Create a new profile with current user
  def create
    @profile = Profile.new(profile_params.merge({user: current_user}))

    if @profile.save
      redirect_to @profile, notice: 'Profile was successfully created.'
    else
      format.html { render :new }
    end
  end

  # Update current users latest profile
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  # Destroy current users latest profile
  def destroy
    @profile.destroy
     redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :abn, :address, :state, :postcode, :mobile_number, :user_id, :picture)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="add_or_edit_profile_form">


  <div class="add_or_edit_profile_form_parts" id="profile_description">
    <div class="field">
      <%= form.label :first_name, class:'label'%>
      <%= form.text_field :first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name, class:'label' %>
      <%= form.text_field :last_name %>
    </div>

    <div class="field">
      <%= form.label :abn, class:'label' %>
      <%= form.text_field :abn %>
    </div>

    <div class="field">
      <%= form.label :address, class:'label' %>
      <%= form.text_field :address %>
    </div>

    <div class="field">
     <%= form.label :state, class:'label' %>
      <%= form.text_field :state %>
    </div>

    <div class="field">
      <%= form.label :suburb, class:'label' %>
      <%= form.text_field :suburb %>
    </div>

    <div class="field">
      <%= form.label :postcode, class:'label' %>
      <%= form.text_field :postcode %>
    </div>

    <div class="field">
     <%= form.label :mobile_number, class:'label' %>
      <%= form.text_field :mobile_number %>
    </div>
  </div>

  <div class="add_or_edit_profile_form_parts" id="profile_picture">
    <div class="field">
      <%= form.file_field :picture %>
    </div>
  </div>

</div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="profile_form">
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>
</div>

<%= link_to 'Back to Profile', @profile %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="all_heading">Plantish Community</div>


<div class="comunity_container">



      <% @profiles.each do |profile| %>
       <div class="one_member">
         <div class="one_member_picture">
          <%= image_tag(profile.picture, width: 200, height: 200) if profile.picture.attached? %><br />
         </div>
         <div class="one_member_description">
            Name: <%= profile.first_name %> <br />
          <% if profile.state.present? %>
              State: <%= profile.state  %>
           <% else  %>
              State: Not Added
          <% end %><br />
            Postcode: <%= profile.postcode %><br/>
            Email address: <%= profile.user.email %>
         </div>
         <%= link_to 'View Products', sellers_product_list_path(profile.user) %>
       </div>

      <% end %>



</div>


<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>First name</th>-->
<!--      <th>Last name</th>-->
<!--      <th>Abn</th>-->
<!--      <th>Address</th>-->
<!--      <th>State</th>-->
<!--      <th>Postcode</th>-->
<!--      <th>Mobile number</th>-->
<!--      <th>User</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
    <%# @profiles.each do |profile| %>
<!--      <tr>-->
<!--        <td><%#= profile.first_name %></td>-->
<!--        <td><%#= profile.last_name %></td>-->
<!--        <td><%#= profile.abn %></td>-->
<!--        <td><%#= profile.address %></td>-->
<!--        <td><%#= profile.state %></td>-->
<!--        <td><%#= profile.postcode %></td>-->
<!--        <td><%#= profile.mobile_number %></td>-->
<!--        <td><%#= profile.user_id %></td>-->
<!--        <td><%#= link_to 'Show', profile %></td>-->
<!--        <td><%#= link_to 'Edit', edit_profile_path(profile) %></td>-->
<!--        <td><%#= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

app/views/profiles/new.html.erb
<div class="profile_form">
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>


</div>
<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<div class="my_profile_container">
  <div class="my_profile_box" id="profile_picture">
    <%= image_tag(@profile.picture, width: 200, height: 200) if @profile.picture.attached? %>
  </div>

  <div class="my_profile_box" id="profile_description">


    <div class="profile_description_box">
      <p>
        <strong>First name:</strong>
        <% if @profile.first_name.present? %>
          <%= @profile.first_name %>
        <% else %>
          First Name Required
        <% end %>
      </p>

      <p>
        <strong>Last name:</strong>
        <% if @profile.last_name.present? %>
          <%= @profile.last_name %>
        <% else %>
          Last Name Required
        <% end %>
      </p>

      <p>
        <strong>ABN: </strong>
        <% if @profile.abn.present? %>
          <%= @profile.abn %>
        <% else %>
          ABN Required
        <% end %>
      </p>
    </div>

    <div class="profile_description_box">

      <p>
        <strong>Address:</strong>
        <% if @profile.address.present? %>
          <%= @profile.address %>
        <% else %>
          Address Required
        <% end %>
      </p>

      <p>
       <strong>State:</strong>
        <% if @profile.state.present? %>
          <%= @profile.state %>
        <% else %>
          State Required
        <% end %>
      </p>

      <p>
       <strong>Suburb:</strong>

        <% if @profile.suburb.present? %>
          <%= @profile.suburb %>
        <% else %>
          Suburb Required
        <% end %>
      </p>


      <p>

        <strong>Postcode:</strong>
        <% if @profile.postcode.present? %>

          <%= @profile.postcode %>
        <% else %>
          Postcode Required
        <% end %>
      </p>



      <p>
        <strong>Mobile number:</strong>
        <% if @profile.mobile_number.present? %>

          <%= @profile.mobile_number %>
        <% else %>
          Mobile number required
        <% end %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @current_user.email %>
      </p>
    </div>
    <p>
<!--  <strong>User:</strong>-->
      <% @profile.user_id %>
    </p>

  </div>
</div>
<%= link_to 'Edit Profile', edit_profile_path(@profile), class:'edit_button' %>