config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :carts
  resources :products
  resources :profiles
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'market#home'
  get '/', to: 'market#home'
  get '/category', to: 'market#home'
  get '/about', to: 'market#about'
  get '/contact', to: 'market#contact'

  get '/categories/:category', to: 'products#category'

  get '/products/seller/:seller_id', to: 'products#sellers_product_list', as: 'sellers_product_list'

  post '/transactions', to: 'transactions#create'

end

app/views/shared/_add_product_to_cart.html.erb
<% if current_user && @profile.present? && @profile.id.present? %>
  <%= form_with(model: @cart, local: true) do |form| %>
    <div class="field" style="visibility: hidden">
      <%= form.label :product_id %>
      <%= form.text_field :product_id, :value => product.id %>
    </div>

    <div class="actions">
      <%= form.submit 'Add to Cart' %>
    </div>
  <% end %>
<% elsif current_user %>
  <%= link_to "Create profile to add to cart", new_profile_path, class: 'signing_for_adding_to_cart' %>
<% else %>
  <%= link_to "Log in to add to cart", new_user_session_path, class: 'signing_for_adding_to_cart' %>
<% end %>

app/views/shared/_banner.html.erb
<div class="banner">

    <%#= image_tag 'banner1.jpg', class: 'banner_pic_single' %>
    <%= image_tag 'banner2.jpg', class: 'banner_pic_single' %>
    <%#= image_tag 'banner3.jpg', class: 'banner_pic_single' %>
    <%#= image_tag 'banner4.jpg', class: 'banner_pic_single' %>
    <%= image_tag 'banner5.jpg', class: 'banner_pic_single' %>
    <%= image_tag 'banner6.jpg', class: 'banner_pic_single' %>
</div>

app/views/shared/_header.html.erb
<div class="navbar">
  <div class="nav_link_wrapper">
    <%= link_to "Home", '/' %>



    <div class="dropdown">
      <div class="nav_category">Categories</div>
      <div class="dropdown-content">
        <a href="/categories/seeds">Seeds</a>
        <a href="/categories/seedlings">Seedlings</a>
        <a href="/categories/smallplants">Small Plants</a>
        <a href="/categories/flowers">Flowers</a>
        <a href="/categories/fruits">Fruits</a>
        <a href="/categories/indoorplants">Indoor Plants</a>
        <a href="/categories/succulents">Succulents</a>
        <a href="/categories/terrariums">Terrariums</a>
        <a href="/categories/vegetables">Vegetables</a>
        <a href="/categories/gardentools">Garden Tools</a>
        <a href="/categories/compost">Household Compost</a>
        <a href="/categories/mulching">Mulching</a>
        <a href="/categories/helpingHand">Helping Hand</a>
      </div>
    </div>



    <% if current_user && @profile.present? && @profile.id.present? %>
      <%= link_to "My Profile", profile_path(@profile) %>
    <% elsif current_user %>
      <%= link_to "Add Profile", new_profile_path %>
    <% end %>

    

    <% if @profile.present? && @profile.id.present?  %>
      <%= link_to "My Product", products_path %>
    <% end %>

    <%= link_to "Our Community", profiles_path %>
    <%= link_to "About us", about_path %>
    <%= link_to "Contact", contact_path %>

  </div>
</div>






<div class="hamburger_dropdown">
  <div class="hamburger_icon"><%= image_tag 'hamburger.png', class: '' %></div>
  <div class="hamburger_dropdown_content">
      <%= link_to "Home", '/' %>
    <% if current_user && @profile.present? && @profile.id.present? %>
      <%= link_to "My Profile", profile_path(@profile) %>
    <% elsif current_user %>
      <%= link_to "Add Profile", new_profile_path %>
    <% end %>



    <% if @profile.present? && @profile.id.present?  %>
      <%= link_to "My Product", products_path %>
    <% end %>

    <%= link_to "Our Community", profiles_path %>
    <%= link_to "About us", about_path %>
    <%= link_to "Contact", contact_path %>
      <div class="dropdown">
        <div class="nav_category_ham">Categories</div>
          <div class="dropdown-content">
          <a href="/categories/seeds">Seeds</a>
          <a href="/categories/seedlings">Seedlings</a>
          <a href="/categories/smallplants">Small Plants</a>
          <a href="/categories/flowers">Flowers</a>
          <a href="/categories/fruits">Fruits</a>
          <a href="/categories/indoorplants">Indoor Plants</a>
          <a href="/categories/succulents">Succulents</a>
          <a href="/categories/vegetables">Vegetables</a>
          <a href="/categories/gardentools">Garden Tools</a>
          </div>
      </div>


  </div>

</div>

<!--&& @product.id.present?-->

app/views/shared/_product.html.erb
<% @products.each do |product| %>
  <div class="add_cart_to_each_product_of_category_page">

    <%= link_to(product) do %>
      <div class="one_category_each_product">
        <div class="one_category_each_product_image">
          <%= image_tag(product.image, width: 200, height: 200) %>
        </div>
        <div class="one_category_each_product_description_1">
          <% if product.title.present? %>
            <h3><%= product.title.capitalize %></h3>
          <% else %>
            <h3>Tile Required</h3>
          <% end %>
          <% if product.category.present? %>
           <h4><%= product.category.capitalize %></h4>
          <% else %>
           Category Required
          <% end %>
          <% if product.price.present? %>
           AUD$<%= product.price %>
          <% else %>
           Price Required
          <% end %>

          <h4>Seller: <%=  product.seller.profile.first_name %></h4>
        </div>

      </div>
    <% end %>


    <% if current_user && @profile.present? && @profile.id.present? %>
      <%= form_with(model: @cart, local: true) do |form| %>
        <div class="field" style="visibility: hidden">
          <%= form.label :product_id %>
          <%= form.text_field :product_id, :value => product.id %>
        </div>

        <div class="actions">
          <%= form.submit 'Add to Cart' %>
        </div>
      <% end %>
    <% elsif current_user %>
      <%= link_to "Create profile to add to cart", new_profile_path, class: 'signing_for_adding_to_cart' %>
    <% else %>
      <%= link_to "Log in to add to cart", new_user_session_path, class: 'signing_for_adding_to_cart' %>
    <% end %>
  </div>
<% end %>