config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  resources :carts
  resources :products
  resources :profiles
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'market#home'
  get '/', to: 'market#home'
  get '/category', to: 'market#home'
  get '/about', to: 'market#about'
  get '/contact', to: 'market#contact'

  get '/categories/:category', to: 'products#category'

  get '/products/seller/:seller_id', to: 'products#sellers_product_list', as: 'sellers_product_list'

  post '/transactions', to: 'transactions#create'

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller, class_name: 'User', optional: false
  has_one_attached :image
  has_many :carts
  validates :title, presence: true
  validates :price, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :image, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # Get current users products
  # Get current users latest profile latest profile as "My profile" link in navigation bar
  def index
    @products = Product.where(seller_id: current_user.id)
    @profile = Profile.where(user: current_user).last
  end

  # Get current users latest profile as "My profile" link in navigation bar
  # Initialise a Cart
  # show each product
  def show
    @profile = Profile.where(user: current_user).last
    @cart = Cart.new
  end

  # Initialise a product
  # Get current users latest profile as "My profile" link in navigation bar
  def new
    @product = Product.new
    @profile = Profile.where(user: current_user).last
  end

  # Get current users latest profile
  def edit
    @profile = Profile.where(user: current_user).last
  end

  # Create a new product with current user as seller
  def create
    @product = Product.new(product_params.merge({seller_id: current_user.id}))

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # Update current users product
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # Destroy current user product
  def destroy
    @product.destroy
     redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  # Get one specific category
  # Get all products of that category
  # Give access of adding to cart for each product of that specific category
  # Get the latest profile of current user
  def category
    @category = params[:category]
    @products = Product.where(category: @category)
    @profile = Profile.where(user: current_user).last
    @cart = Cart.new
  end

  # Get the name and all products of a specific seller
  # Give access to cart to all the products of that seller
  # Get the latest profile of current user
  def sellers_product_list
    seller_id = params[:seller_id]
    @products = Product.where(seller_id: seller_id)
    @profile = Profile.where(user: current_user).last
    @seller_name = Profile.where(user_id: seller_id).first.first_name
    @cart = Cart.new
  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :category, :price, :description, :seller_id, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>





  <div class="new_product_form">
    <div class="new_product_form_parts" id="part2">
      <div class="form_parts">
        <h4>Upload product image </h4>
        <%= form.file_field :image %>

      </div>
    </div>

    <div class="new_product_form_parts" id="part1">
      <div class="form_parts">
        <h3>Name of the product </h3>
        <%= form.text_field :title %>
      </div>

      <div class="form_parts">
        <h4>Category </h4>
        <%= form.select(:category, [['Flowers', 'flowers'], ['Fruits', 'fruits'], ['Vegetables', 'vegetables'], ['Seeds', 'seeds'], ['Seedlings', 'seedlings'], ['Small Plants', 'smallplants'], ['Indoor Plants', 'indoorplants'], ['Succulents', 'succulents'], ['Garden Tools', 'gardentools'], ['Terrariums', 'terrariums'], ['Compost', 'compost'], ['Mulching', 'mulching'], ['Helping hand', 'helpingHand']]) %>
      </div>
      <div class="form_parts">
        <h4>Add Price</h4>
        <%= form.number_field :price %>
      </div>
      <div class="form_parts">
        <h4>Describe the product</h4>
        <%= form.text_area :description %>
      </div>
        <%= form.submit %>
    </div>
  </div>




<% end %>

app/views/products/category.html.erb
<%= render 'shared/banner' %>
<div class="all_heading"><%= @category.upcase  %></div>
<div class="one_category_page">
  <%= render 'shared/product' %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="all_heading">My Products</div>

<div class="newproduct"><%= link_to ' Add A New Product', new_product_path %></div>

<div class="one_category_page" id="allofmyproduct">
  <% @products.each do |product| %>


    <%= link_to(product) do %>
      <div class="one_category_each_product" id="myproduct">

        <div class="one_category_each_product_image">
          <%= image_tag(product.image, width: 200, height: 200) %>
        </div>


        <div class="one_category_each_product_description_1">
          <% if product.title.present? %>
            <h3><%= product.title.capitalize %></h3>
          <% else %>
            <h3>Tile Required</h3>
          <% end %>
          <% if product.category.present? %>
            <h4><%= product.category.capitalize %></h4>
          <% else %>
            Category Required
          <% end %><br />

          <% if product.price.present? %>
            AUD$<%= product.price %>
          <% else %>
            Price Required
          <% end %>
        </div>


        <div class="product_access_button">

            <%= image_tag 'deeletebutton.png', class: 'control_image_button' %>
            <%= link_to 'Delete product?', product, method: :delete, data: { confirm: 'Are you sure?' } %>
         
        </div>

        <div class="product_access_button">
          <%= image_tag 'editbutton.png', class: 'control_image_button' %>
          <%= link_to 'Edit Product', edit_product_path(product), class:'control_image_button' %>
        </div>
      </div>
    <% end %>


  <% end %>



</div>



<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/sellers_product_list.html.erb
<%= render 'shared/banner' %>

<div class="all_heading">Products of <%=  @seller_name %></div>

<div class="one_category_page">
  <%= render 'shared/product' %>

</div>
</div>

app/views/products/show.html.erb
<%= render 'shared/banner' %>
<div class="each_product_show">
  <div class="each_product_show_box">
    <%= image_tag(@product.image, width: 400, height: 400) %>
  </div>
  <div class="each_product_show_box">
    <div class="each_product_show_box_parts">
      <% if @product.title.present? %>
        <h1><%= @product.title.capitalize %></h1>
     <% else %>
        <h1>Tile Required</h1>
      <% end %><br />
    </div>
    <div class="each_product_show_box_parts">
      <% if @product.category.present? %>
        <h3><%= @product.category.capitalize %></h3>
      <% else %>
        Category Required
      <% end %><br />
      <% if @product.price.present? %>
        <strong>AUD$</strong><%= @product.price %>
      <% else %>
        Price Required
      <% end %><br />
    </div>
    <div class="each_product_show_box_parts">
      <% if @product.description.present? %>
        <%= @product.description %>
      <% else %>
        Product Description Required
      <% end %><br />
    </div>

    <div class="each_product_show_box_parts">
      Seller name <%=  @product.seller.profile.first_name %>
      </div>

    <div class="each_product_show_box_parts">
     <% if current_user != @product.seller %>
      <% if current_user && @profile.present? && @profile.id.present? %>
        <%= form_with(model: @cart, local: true) do |form| %>
            <div class="field" style="visibility: hidden">
              <%= form.label :product_id %>
              <%= form.text_field :product_id, :value => @product.id %>
            </div>


            <div class="actions">
             <%= form.submit 'Add to Cart' %>
            </div>
        <% end %>
      <% elsif current_user %>
        <%= link_to "Create profile to add to cart", new_profile_path, class: 'signing_for_adding_to_cart' %>
      <% else %>
        <%= link_to "Log in to add to cart", new_user_session_path, class: 'signing_for_adding_to_cart' %>
      <% end %>
     <% end %>
    </div>

  </div>


</div>




<!--<form action="/carts" accept-charset="UTF-8" method="post">-->

<!--  <div class="field">-->
<!--    <label for="cart_product_id">Product</label>-->
<!--    <input type="text" name="cart[product_id]" id="cart_product_id">-->
<!--  </div>-->

<!--  <div class="field">-->
<!--    <label for="cart_buyer_id">Buyer</label>-->
<!--    <input type="text" name="cart[buyer_id]" id="cart_buyer_id">-->
<!--  </div>-->

<!--  <div class="actions">-->
<!--    <input type="submit" name="commit" value="Create Cart" data-disable-with="Create Cart">-->
<!--  </div>-->
<!--</form>-->



<p id="notice"><%= notice %></p>





<!--<div class="product_access_button">-->
<!--  <div class="one_button">-->
    <%#= link_to 'Edit Product', edit_product_path(product) %>
<!--  </div>-->
<!--  <div class="one_button">-->
    <%#= link_to 'Delete Product', product, method: :delete, data: { confirm: 'Are you sure?' } %>
<!--  </div>-->
<!--</div>-->